import queue as q

customQueue = q.Queue(maxsize=3)
print(customQueue.qsize())
print("-----------------------")
print(customQueue.empty())
print("-----------------------")
customQueue.put(1)
customQueue.put(2)
customQueue.put(3)
print(customQueue.qsize())
print("-----------------------")
print(customQueue.full())
print("-----------------------")
print(customQueue.get())
print("-----------------------")
print(customQueue.qsize())